GET http://localhost:5000/api/brands

###

GET http://localhost:5000/api/brands/3

###

POST http://localhost:5000/brands
Content-Type: application/json

{
  "title": "Meizu",
  "description": "Meizu Corparation"
}

###

PUT http://localhost:5000/brands
Content-Type: application/json

{
  "id": 4,
  "title": "Meizu updated",
  "description": "Meizu Corparation"
}

###

DELETE http://localhost:5000/brands/4