GET http://localhost:5000/api/orders

###

GET http://localhost:5000/api/orders/2

###

POST http://localhost:5000/api/orders
Content-Type: application/json

{
  "code": "ORD011",
  "date": "2024-07-27T06:34:02.380Z",
  "amount": 150,
  "paid": false,
  "customer": "Jane Doe"
}

###

PUT http://localhost:5000/api/orders
Content-Type: application/json

{
  "id": 12,
  "code": "ORD012",
  "date": "2024-07-27T06:34:02.380Z",
  "customer": "Jane Doe",
  "amount": 500,
  "paid": false,
  "updatedAt": "2024-07-31T18:49:19.800Z",
  "createdAt": "2024-07-31T18:49:19.800Z"
}

###

DELETE http://localhost:5000/api/orders/12